
test: machine.h machine.c ../tape/tape.c ../buffer/buffer.c ../element/element.c 
	gcc -I../element/ -I../tape/ -I../buffer/ ../buffer/buffer.c ../element/element.c ../tape/tape.c machine.c machine.test.c -o test

