

 /* Java code generated by "translate.java.pss" */
 import java.io.*;
 import java.util.regex.*;
 import java.util.*;   // contains stack

 public class jsonparse {
   // using int instead of char so that all unicode code points are
   // available instead of just utf16. (emojis cant fit into utf16)
   private int accumulator;         // counter for anything
   private int peep;                // next char in input stream
   private int charsRead;           // No. of chars read so far
   private int linesRead;           // No. of lines read so far
   public StringBuffer workspace;    // text accumulator
   private Stack<String> stack;      // parse token stack
   private int LENGTH;               // tape initial length

   // use ArrayLists instead with .add() .get(n) and .set(n, E)
   // ArrayList<StringBuffer> al=new ArrayList<StringBuffer>();
   private List<StringBuffer> tape;      // array of token attributes 
   private List<StringBuffer> marks;     // tape marks
   private int tapePointer;          // pointer to current cell
   private Reader input;             // text input stream
   private boolean eof;              // end of stream reached?
   private boolean flag;             // not used here
   private StringBuffer escape;    // char used to "escape" others "\"
   private StringBuffer delimiter; // push/pop delimiter (default is "*")
   private boolean markFound;      // if the mark was found in tape
   
   /** make a new machine with a character stream reader */
   public jsonparse(Reader reader) {
     this.markFound = false; 
     this.LENGTH = 100;
     this.input = reader;
     this.eof = false;
     this.flag = false;
     this.charsRead = 0; 
     this.linesRead = 1; 
     this.escape = new StringBuffer("\\");
     this.delimiter = new StringBuffer("*");
     this.accumulator = 0;
     this.workspace = new StringBuffer("");
     this.stack = new Stack<String>();
     this.tapePointer = 0;
     this.tape = new ArrayList<StringBuffer>();
     this.marks = new ArrayList<StringBuffer>();
     for (int ii = 0; ii < this.LENGTH; ii++) {
       this.tape.add(new StringBuffer(""));
       this.marks.add(new StringBuffer(""));
     }

     try
     { this.peep = this.input.read(); } 
     catch (java.io.IOException ex) {
       System.out.println("read error");
       System.exit(-1);
     }
   }

   /** read one character from the input stream and 
       update the machine. */
   public void read() {
     int iChar;
     try {
       if (this.eof) { System.exit(0); }
       this.charsRead++;
       // increment lines
       if ((char)this.peep == '\n') { this.linesRead++; }
       this.workspace.append(Character.toChars(this.peep));
       this.peep = this.input.read(); 
       if (this.peep == -1) { this.eof = true; }
     }
     catch (IOException ex) {
       System.out.println("Error reading input stream" + ex);
       System.exit(-1);
     }
   }

   /** increment tape pointer by one */
   public void increment() {
     this.tapePointer++;
     if (this.tapePointer >= this.LENGTH) {
       this.tape.add(new StringBuffer(""));
       this.marks.add(new StringBuffer(""));
       this.LENGTH++;
     }
   }
   
   /** remove escape character  */
   public void unescapeChar(char c) {
     if (workspace.length() > 0) {
       String s = this.workspace.toString().replace("\\"+c, c+"");
       this.workspace.setLength(0); workspace.append(s);
     }
   }

   /** add escape character  */
   public void escapeChar(char c) {
     if (workspace.length() > 0) {
       String s = this.workspace.toString().replace(c+"", "\\"+c);
       workspace.setLength(0); workspace.append(s);
     }
   }

   /** whether trailing escapes \\ are even or odd */
   // untested code. check! eg try: add "x \\"; print; etc
   public boolean isEscaped(String ss, String sSuffix) {
     int count = 0; 
     if (ss.length() < 2) return false;
     if (ss.length() <= sSuffix.length()) return false;
     if (ss.indexOf(this.escape.toString().charAt(0)) == -1) 
       { return false; }

     int pos = ss.length()-sSuffix.length();
     while ((pos > -1) && (ss.charAt(pos) == this.escape.toString().charAt(0))) {
       count++; pos--;
     }
     if (count % 2 == 0) return false;
     return true;
   }

   /* a helper to see how many trailing \\ escape chars */
   private int countEscaped(String sSuffix) {
     String s = "";
     int count = 0;
     int index = this.workspace.toString().lastIndexOf(sSuffix);
     // remove suffix if it exists
     if (index > 0) {
       s = this.workspace.toString().substring(0, index);
     }
     while (s.endsWith(this.escape.toString())) {
       count++;
       s = s.substring(0, s.lastIndexOf(this.escape.toString()));
     }
     return count;
   }

   /** reads the input stream until the workspace end with text */
   // can test this with
   public void until(String sSuffix) {
     // read at least one character
     if (this.eof) return; 
     this.read();
     while (true) {
       if (this.eof) return;
       if (this.workspace.toString().endsWith(sSuffix)) {
         if (this.countEscaped(sSuffix) % 2 == 0) { return; }
       }
       this.read();
     }
   }

   /** pop the first token from the stack into the workspace */
   public Boolean pop() {
     if (this.stack.isEmpty()) return false;
     this.workspace.insert(0, this.stack.pop());     
     if (this.tapePointer > 0) this.tapePointer--;
     return true;
   }

   /** push the first token from the workspace to the stack */
   public Boolean push() {
     String sItem;
     // dont increment the tape pointer on an empty push
     if (this.workspace.length() == 0) return false;
     // need to get this from this.delim not "*"
     int iFirstStar = 
       this.workspace.indexOf(this.delimiter.toString());
     if (iFirstStar != -1) {
       sItem = this.workspace.toString().substring(0, iFirstStar + 1);
       this.workspace.delete(0, iFirstStar + 1);
     }
     else {
       sItem = this.workspace.toString();
       this.workspace.setLength(0);
     }
     this.stack.push(sItem);     
     this.increment(); 
     return true;
   }

   /** swap current tape cell with the workspace */
   public void swap() {
     String s = new String(this.workspace);
     this.workspace.setLength(0);
     this.workspace.append(this.tape.get(this.tapePointer).toString());
     this.tape.get(this.tapePointer).setLength(0);
     this.tape.get(this.tapePointer).append(s);
   }

   /** save the workspace to file "sav.pp" */
   public void writeToFile() {
     try {
       File file = new File("sav.pp");
       Writer out = new BufferedWriter(new OutputStreamWriter(
          new FileOutputStream(file), "UTF8"));
       out.append(this.workspace.toString());
       out.flush(); out.close();
     } catch (Exception e) { 
       System.out.println(e.getMessage());
     }
   }

   public void goToMark(String mark) {
     this.markFound = false; 
     for (var ii = 0; ii < this.marks.size(); ii++) {
       if (this.marks.get(ii).toString().equals(mark)) { 
         this.tapePointer = ii; this.markFound = true; 
       }
     }
     if (this.markFound == false) { 
       System.out.print("badmark '" + mark + "'!"); 
       System.exit(1);
     }
   }

   /** parse/check/compile the input */
   public void parse(InputStreamReader input) {
     //this is where the actual parsing/compiling code should go 
     //but this means that all generated code must use
     //"this." not "mm."
   }

  public static void main(String[] args) throws Exception { 
    String temp = "";    
    jsonparse mm = new jsonparse(new InputStreamReader(System.in)); 

    script: 
    while (!mm.eof) {
      lex: { 
        mm.read(); /* read */
        // Unlike Crockfords grammar, I will just completely ignore whitespace,
        // but this may not be acceptable in a rigorous application. Also, I
        // am just using the ctype.h definition of whitespace, whatever that 
        // may be.
        if (mm.workspace.toString().matches("^\\p{Space}+$")) {
          mm.workspace.setLength(0);            /* clear */
          break lex;
        }
        if (mm.workspace.toString().matches("^[0-9]+$")) {
          /* while */ 
          while (Character.toString((char)mm.peep).matches("^[0-9]+$")) { if (mm.eof) { break; } mm.read(); }
          mm.tape.get(mm.tapePointer).setLength(0); /* put */
          mm.tape.get(mm.tapePointer).append(mm.workspace); 
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append("number*"); /* add */
          mm.push();
          break lex;
        }
        if (mm.workspace.toString().matches("^[a-z]+$")) {
          /* while */ 
          while (Character.toString((char)mm.peep).matches("^[a-z]+$")) { if (mm.eof) { break; } mm.read(); }
          if (!mm.workspace.toString().equals("true") && !mm.workspace.toString().equals("false") && !mm.workspace.toString().equals("null")) {
            // handle error
            mm.tape.get(mm.tapePointer).setLength(0); /* put */
            mm.tape.get(mm.tapePointer).append(mm.workspace); 
            mm.workspace.setLength(0);            /* clear */
            mm.workspace.append("Unknown value '"); /* add */
            mm.workspace.append(mm.tape.get(mm.tapePointer)); /* get */
            mm.workspace.append("' at line "); /* add */
            mm.workspace.append(mm.linesRead); /* lines */
            mm.workspace.append(" (character "); /* add */
            mm.workspace.append(mm.charsRead); /* chars */
            mm.workspace.append(").\n"); /* add */
            System.out.print(mm.workspace); /* print */
            break script;
          }
          mm.tape.get(mm.tapePointer).setLength(0); /* put */
          mm.tape.get(mm.tapePointer).append(mm.workspace); 
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append("value*"); /* add */
          mm.push();
          break lex;
        }
        if (mm.workspace.toString().equals("\"")) {
          // save line number for error message
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append(mm.linesRead); /* lines */
          mm.tape.get(mm.tapePointer).setLength(0); /* put */
          mm.tape.get(mm.tapePointer).append(mm.workspace); 
          mm.workspace.setLength(0);            /* clear */
          mm.until("\"");
          if (mm.eof) {
            mm.workspace.setLength(0);            /* clear */
            mm.workspace.append("Unterminated \" char, at line "); /* add */
            mm.workspace.append(mm.tape.get(mm.tapePointer)); /* get */
            mm.workspace.append("\n"); /* add */
            System.out.print(mm.workspace); /* print */
            break script;
          }
          if (mm.workspace.length() > 0) { /* clip */
            mm.workspace.delete(mm.workspace.length() - 1, 
            mm.workspace.length()); }
          mm.tape.get(mm.tapePointer).setLength(0); /* put */
          mm.tape.get(mm.tapePointer).append(mm.workspace); 
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append("string*"); /* add */
          mm.push();
          break lex;
        }
        // literal tokens
        if (mm.workspace.toString().equals(",") || mm.workspace.toString().equals(":") || mm.workspace.toString().equals("-") || mm.workspace.toString().equals("+") || mm.workspace.toString().equals("[") || mm.workspace.toString().equals("]") || mm.workspace.toString().equals("{") || mm.workspace.toString().equals("}")) {
          mm.tape.get(mm.tapePointer).setLength(0); /* put */
          mm.tape.get(mm.tapePointer).append(mm.workspace); 
          mm.workspace.append("*"); /* add */
          mm.push();
          break lex;
        }
      }
      parse: 
      while (true) { 
        // The parse/compile phase
        // --------------
        // 2 tokens
        mm.pop();
        mm.pop();
        // comma errors 
        if (mm.workspace.toString().equals("{*,*") || mm.workspace.toString().equals(",*}*") || mm.workspace.toString().equals("[*,*") || mm.workspace.toString().equals(",*,*") || mm.workspace.toString().equals(",*]*")) {
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append("Misplaced , at line "); /* add */
          mm.workspace.append(mm.linesRead); /* lines */
          mm.workspace.append(" ?(char "); /* add */
          mm.workspace.append(mm.charsRead); /* chars */
          mm.workspace.append(")\n"); /* add */
          System.out.print(mm.workspace); /* print */
          break script;
        }
        // catch object member errors 
        // also need to check that not only 1 token in on the stack
        // hence the !"member*" construct
        if (mm.workspace.toString().startsWith("member*") || mm.workspace.toString().startsWith("members*")) {
          if (!mm.workspace.toString().equals("member*") && !mm.workspace.toString().equals("members*") && !mm.workspace.toString().endsWith(",*") && !mm.workspace.toString().endsWith("}*")) {
            mm.workspace.setLength(0);            /* clear */
            mm.workspace.append("Error after object member near line "); /* add */
            mm.workspace.append(mm.linesRead); /* lines */
            mm.workspace.append(" (char "); /* add */
            mm.workspace.append(mm.charsRead); /* chars */
            mm.workspace.append(")\n"); /* add */
            System.out.print(mm.workspace); /* print */
            break script;
          }
        }
        // catch array errors 
        if (mm.workspace.toString().startsWith("items*")) {
          if (!mm.workspace.toString().equals("items*") && !mm.workspace.toString().endsWith(",*") && !mm.workspace.toString().endsWith("]*")) {
            mm.workspace.setLength(0);            /* clear */
            mm.workspace.append("Error after an array item near line "); /* add */
            mm.workspace.append(mm.linesRead); /* lines */
            mm.workspace.append(" (char "); /* add */
            mm.workspace.append(mm.charsRead); /* chars */
            mm.workspace.append(")\n"); /* add */
            System.out.print(mm.workspace); /* print */
            break script;
          }
        }
        if (mm.workspace.toString().startsWith("array*") || mm.workspace.toString().startsWith("object*")) {
          if (!mm.workspace.toString().equals("array*") && !mm.workspace.toString().equals("object*") && !mm.workspace.toString().endsWith(",*") && !mm.workspace.toString().endsWith("}*") && !mm.workspace.toString().endsWith("]*")) {
            mm.workspace.setLength(0);            /* clear */
            mm.workspace.append("Error after array or object near line "); /* add */
            mm.workspace.append(mm.linesRead); /* lines */
            mm.workspace.append(" (char "); /* add */
            mm.workspace.append(mm.charsRead); /* chars */
            mm.workspace.append(")\n"); /* add */
            System.out.print(mm.workspace); /* print */
            break script;
          }
        }
        // invalid string sequence
        if (mm.workspace.toString().startsWith("string*")) {
          if (!mm.workspace.toString().equals("string*") && !mm.workspace.toString().endsWith(",*") && !mm.workspace.toString().endsWith("]*") && !mm.workspace.toString().endsWith("}*") && !mm.workspace.toString().endsWith(":*")) {
            mm.workspace.setLength(0);            /* clear */
            mm.workspace.append("Error after a string near line "); /* add */
            mm.workspace.append(mm.linesRead); /* lines */
            mm.workspace.append(" (char "); /* add */
            mm.workspace.append(mm.charsRead); /* chars */
            mm.workspace.append(")\n"); /* add */
            System.out.print(mm.workspace); /* print */
            break script;
          }
        }
        // transmogrify into array item, start array
        if (mm.workspace.toString().equals("[*number*") || mm.workspace.toString().equals("[*string*") || mm.workspace.toString().equals("[*value*") || mm.workspace.toString().equals("[*array*") || mm.workspace.toString().equals("[*object*")) {
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append("[*items*"); /* add */
          mm.push();
          mm.push();
          continue parse;
        }
        // signed numbers
        if (mm.workspace.toString().equals("-*number*")) {
          /* nop: no-operation eliminated */
        }
        // empty arrays are legal json
        if (mm.workspace.toString().equals("[*]*")) {
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append("array*"); /* add */
          mm.push();
          continue parse;
        }
        // empty objects are legal json
        if (mm.workspace.toString().equals("{*}*")) {
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append("object*"); /* add */
          mm.push();
          continue parse;
        }
        // --------------
        // 3 tokens
        mm.pop();
        // arrays, 
        if (mm.workspace.toString().equals("[*items*]*")) {
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append("array*"); /* add */
          mm.push();
          continue parse;
        }
        // 
        if (mm.workspace.toString().equals("items*,*number*") || mm.workspace.toString().equals("items*,*string*") || mm.workspace.toString().equals("items*,*value*") || mm.workspace.toString().equals("items*,*array*") || mm.workspace.toString().equals("items*,*object*")) {
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append("items*"); /* add */
          mm.push();
          continue parse;
        }
        // object members
        if (mm.workspace.toString().equals("string*:*number*") || mm.workspace.toString().equals("string*:*string*") || mm.workspace.toString().equals("string*:*value*") || mm.workspace.toString().equals("string*:*object*") || mm.workspace.toString().equals("string*:*array*")) {
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append("member*"); /* add */
          mm.push();
          continue parse;
        }
        // multiple elements of an object
        if (mm.workspace.toString().equals("member*,*member*") || mm.workspace.toString().equals("members*,*member*")) {
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append("members*"); /* add */
          mm.push();
          continue parse;
        }
        //  
        if (mm.workspace.toString().equals("{*members*}*") || mm.workspace.toString().equals("{*member*}*")) {
          mm.workspace.setLength(0);            /* clear */
          mm.workspace.append("object*"); /* add */
          mm.push();
          continue parse;
        }
        mm.push();
        mm.push();
        mm.push();
        if (mm.eof) {
          while (mm.pop());          /* unstack */
          if (mm.workspace.toString().equals("object*") || mm.workspace.toString().equals("array*") || mm.workspace.toString().equals("value*") || mm.workspace.toString().equals("string*") || mm.workspace.toString().equals("number*")) {
            while(mm.push());          /* stack */
            mm.workspace.append("Valid json! Top level item was '"); /* add */
            System.out.print(mm.workspace); /* print */
            mm.workspace.setLength(0);            /* clear */
            mm.pop();
            if (mm.workspace.length() > 0) { /* clip */
              mm.workspace.delete(mm.workspace.length() - 1, 
              mm.workspace.length()); }
            mm.workspace.append("'\n"); /* add */
            System.out.print(mm.workspace); /* print */
            mm.workspace.setLength(0);            /* clear */
            break script;
          }
          while(mm.push());          /* stack */
          mm.workspace.append("Maybe not valid json.\n"); /* add */
          mm.workspace.append("The parse stack was \n"); /* add */
          System.out.print(mm.workspace); /* print */
          mm.workspace.setLength(0);            /* clear */
          while (mm.pop());          /* unstack */
          mm.workspace.append("\n"); /* add */
          System.out.print(mm.workspace); /* print */
        }
        break parse;
      }
    }
  }
}
